#! /bin/sh
### BEGIN INIT INFO
# Provides:          sp-policyd
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: sentora-paranoid SMTP policy daemon
# Description:       script to set mail users quota
### END INIT INFO
#
# Author:	Mario Ricardo Rodriguez Somohano, sentora-paranoid(at)open-source.tk
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/sbin/sp-policyd.pl
PIDFILE=/var/run/sp-policyd.pl.pid
LOGFILE=/var/sentora/logs/sp-policyd.log

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting SMTP policy daemon" "sp-policyd"
	start_daemon -p $PIDFILE $DAEMON
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping SMTP policy daemon" "sp-policyd"
	killproc -p $PIDFILE $DAEMON
	log_end_msg $?
    ;;
  restart)
    $0 stop
	sleep 2
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON printshm && exit 0 || exit $?
    ;;
  clean)
	truncate -s 0 $LOGFILE
	log_daemon_msg "Cleaning log file"  "sp-policyd"
	log_end_msg $?
    ;;
  *)
    echo "Usage: /etc/init.d/sp-policyd {start|stop|restart|status|clean}"
    exit 1
    ;;
esac

exit 0
